# Usa uma imagem leve do Node.js
FROM node:20-alpine

# Define a pasta de trabalho dentro do container
WORKDIR /app

# Copia os arquivos de dependência
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o resto do projeto
COPY . .

# Expõe a porta do Vite
EXPOSE 5173

# Comando para rodar o Vite liberando o IP local
CMD ["npm", "run", "dev", "--", "--host"]