services:
  db:
    image: postgres:15-alpine
    container_name: samu-db
    restart: always
    environment:
      POSTGRES_USER: samu
      POSTGRES_PASSWORD: samu
      POSTGRES_DB: samu
    ports:
      - "5490:5432" # Deixamos o banco na 5490 fixa para você acessar no DBeaver
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d/

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: samu-api
    restart: always
    ports:
      - "${FICHA_SAMU_BACK}:3001" # API usa a porta 8026
    environment:
      - DB_HOST=db 
    volumes:
      - ./:/app 
      - /app/node_modules 
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: samu-frontend
    restart: always
    ports:
      - "8765:5173" # Frontend usa a porta 8765
    volumes:
      - ./:/app 
      - /app/node_modules 
    depends_on:
      - api

volumes:
  pgdata: