CREATE TABLE criterios_avaliacao (
    id SERIAL PRIMARY KEY,
    tipo VARCHAR(50) NOT NULL,
    categoria VARCHAR(100) NOT NULL,
    codigo VARCHAR(20) NOT NULL,
    criterio TEXT NOT NULL,
    peso INTEGER NOT NULL,
    indicador VARCHAR(100),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	avaliacao VARCHAR(100),
);

INSERT INTO public.criterios_avaliacao (tipo,categoria,codigo,criterio,indicador,ativo,created_at,peso,avaliacao) VALUES
	 ('Condutor','Técnico Operacional','ABC1','Realiza o checklist completo da viatura no início do plantão (combustível, pneus, equipamentos, kit de emergência).',NULL,false,'2026-06-16 13:01:16.376169',1,'Lider > Liderado'),
	 ('Condutor','Técnico Operacional','ABC2','Mantém a ambulância limpa, organizada e em condições sanitárias adequadas após cada atendimento.',NULL,false,'2026-06-16 13:01:16.376169',1,'Lider > Liderado'),
	 ('Condutor','Técnico Operacional','ABC3','Pratica direção defensiva com habilidade, respeitando sinalização e garantindo a segurança da equipe e do paciente no deslocamento de emergência.',NULL,false,'2026-06-16 13:01:16.376169',1,'Lider > Liderado'),
	 ('Condutor','Técnico Operacional','ABC4','Conhece e utiliza corretamente rotas de acesso, vias alternativas e GPS para otimização do tempo-resposta.',NULL,false,'2026-06-16 13:01:16.376169',1,'Lider > Liderado'),
	 ('Condutor','Técnico Operacional','ABC5','Auxilia a equipe nos procedimentos de Suporte Básico de Vida (SBV): RCP, imobilização e oxigenoterapia básica.',NULL,false,'2026-06-16 13:01:16.376169',1,'Lider > Liderado'),
	 ('Condutor','Técnico Operacional','ABC6','Manuseia corretamente a maca, cadeira de rodas, prancha longa e colar cervical.',NULL,false,'2026-06-16 13:01:16.376169',1,'Lider > Liderado'),
	 ('Condutor','Comportamental','ABC7','Integra-se ativamente à equipe, antecipando necessidades, cooperando na cena e comunicando informações relevantes.',NULL,false,'2026-06-16 13:01:16.376169',1,'Lider > Liderado'),
	 ('Condutor','Comportamental','ABC8','Comunica-se de forma clara e objetiva com a equipe e com a Central de Regulação (CRUR-BF) durante o atendimento.',NULL,false,'2026-06-16 13:01:16.376169',1,'Lider > Liderado'),
	 ('Condutor','Comportamental','ABC9','Avalia a segurança da cena antes de se aproximar e comunica os riscos à equipe (tráfego, violência, substâncias).',NULL,false,'2026-06-16 13:01:16.376169',1,'Lider > Liderado'),
	 ('Condutor','Comportamental','BBC1','Mantém controle emocional em cenários de alta tensão, múltiplas vítimas, violência ou óbito.',NULL,false,'2026-06-16 13:01:16.376169',1,'Lider > Liderado');
INSERT INTO public.criterios_avaliacao (tipo,categoria,codigo,criterio,indicador,ativo,created_at,peso,avaliacao) VALUES
	 ('Condutor','Comportamental','BBC2','Trata pacientes, familiares e equipe com respeito, sigilo e ética, preservando a dignidade humana.',NULL,false,'2026-06-16 13:01:16.376169',1,'Lider > Liderado'),
	 ('Condutor','Comportamental','BBC3','Administra o tempo de forma racional, cumprindo os prazos e determinações estabelecidas.',NULL,false,'2026-06-16 13:01:16.376169',1,'Lider > Liderado'),
	 ('Condutor','Processo e Qualidade','BBC4','Preenche corretamente o registro de saída e chegada da viatura, tempo de deslocamento e ocorrências relevantes.',NULL,false,'2026-06-16 13:01:16.376169',1,'Lider > Liderado'),
	 ('Condutor','Processo e Qualidade','BBC5','Contribui para o cumprimento do tempo-resposta ≤ 15 minutos da central ao local (parâmetro SAMU/Portaria 2.048).',NULL,false,'2026-06-16 13:01:16.376169',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Técnico / Clínico','BBC1','Realiza a avaliação primária (ABCDE) de forma rápida, sistemática e correta após chegada na cena.',NULL,false,'2026-06-16 13:09:10.993845',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Técnico / Clínico','BBC2','Executa corretamente compressões torácicas, ventilação (bolsa-valva-máscara) e desfibrilação com DEA.',NULL,false,'2026-06-16 13:09:10.993845',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Técnico / Clínico','BBC3','Realiza punção venosa periférica e administra medicamentos conforme prescrição do enfermeiro/médico.',NULL,false,'2026-06-16 13:09:10.993845',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Técnico / Clínico','BBC4','Manuseia corretamente os equipamentos da USB/USA: oxímetro, monitor cardíaco, respirador e glicosímetro.',NULL,false,'2026-06-16 13:09:10.993845',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Técnico / Clínico','BBC5','Realiza imobilização adequada de vítimas de trauma (colar cervical, prancha, talas) conforme protocolo PHTLS.',NULL,false,'2026-06-16 13:09:10.993845',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Técnico / Clínico','BBC6','Conhece e segue os protocolos clínicos do SAMU-192 (sepse, IAM, AVC, trauma, PCR, intoxicação).',NULL,false,'2026-06-16 13:09:10.993845',1,'Lider > Liderado');
INSERT INTO public.criterios_avaliacao (tipo,categoria,codigo,criterio,indicador,ativo,created_at,peso,avaliacao) VALUES
	 ('Técnico de Enfermagem','Comportamental','COM1','Mantém apresentação pessoal adequada ao cargo e à função.',NULL,false,'2026-06-16 13:09:10.993845',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Comportamental','COM2','Mantém relacionamento respeitoso com pacientes, familiares e colegas de trabalho.',NULL,false,'2026-06-16 13:09:10.993845',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Comportamental','COM3','Demonstra responsabilidade e comprometimento com suas atividades.',NULL,false,'2026-06-16 13:09:10.993845',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Comportamental','COM4','Recebe orientações e feedbacks de forma profissional e com abertura para crescimento.',NULL,false,'2026-06-16 13:09:10.993845',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Comportamental','COM5','Age com ética e discrição no exercício da função.',NULL,false,'2026-06-16 13:09:10.993845',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Comportamental','COM6','Mantém controle emocional e profissionalismo em situações de alta pressão.',NULL,false,'2026-06-16 13:09:10.993845',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Liderança Situacional','LS1','Participa ativamente do trabalho em equipe, comunicando e recebendo informações de forma clara e organizada.',NULL,false,'2026-06-16 13:09:10.993845',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Liderança Situacional','LS2','Mantém atenção à situação da ocorrência, acompanhando o estado do paciente, os equipamentos e as condições do ambiente.',NULL,false,'2026-06-16 13:09:10.993845',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Liderança Situacional','LS3','Demonstra compromisso com a segurança, utilizando corretamente os EPIs e adotando medidas de proteção para si, para o paciente e para a equipe.',NULL,false,'2026-06-16 13:09:10.993845',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Liderança Situacional','LS4','Mantém foco e equilíbrio emocional em situações de pressão, agindo com profissionalismo e respeito.',NULL,false,'2026-06-16 13:09:10.993845',1,'Lider > Liderado');
INSERT INTO public.criterios_avaliacao (tipo,categoria,codigo,criterio,indicador,ativo,created_at,peso,avaliacao) VALUES
	 ('Técnico de Enfermagem','Processo e Qualidade','PQ1','Preenche corretamente os registros de atendimento com informações precisas e no tempo adequado.',NULL,false,'2026-06-16 13:09:10.993845',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Processo e Qualidade','PQ2','Executa o transporte seguro de pacientes críticos, sem agravar lesões existentes.',NULL,false,'2026-06-16 13:09:10.993845',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Técnico / Clínico','BBC1','Realiza a avaliação primária (ABCDE) de forma rápida, sistemática e correta após chegada na cena.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Técnico / Clínico','BBC2','Executa corretamente compressões torácicas, ventilação (bolsa-valva-máscara) e desfibrilação com DEA.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Técnico / Clínico','BBC3','Realiza punção venosa periférica e administra medicamentos conforme prescrição do enfermeiro/médico.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Técnico / Clínico','BBC4','Manuseia corretamente os equipamentos da USB/USA: oxímetro, monitor cardíaco, respirador e glicosímetro.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Técnico / Clínico','BBC5','Realiza imobilização adequada de vítimas de trauma (colar cervical, prancha, talas) conforme protocolo PHTLS.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Técnico / Clínico','BBC6','Conhece e segue os protocolos clínicos do SAMU-192 (sepse, IAM, AVC, trauma, PCR, intoxicação).',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Comportamental','COM1','Mantém apresentação pessoal adequada ao cargo e à função.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Comportamental','COM2','Mantém relacionamento respeitoso com pacientes, familiares e colegas de trabalho.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado');
INSERT INTO public.criterios_avaliacao (tipo,categoria,codigo,criterio,indicador,ativo,created_at,peso,avaliacao) VALUES
	 ('Técnico de Enfermagem','Comportamental','COM3','Demonstra responsabilidade e comprometimento com suas atividades.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Comportamental','COM4','Recebe orientações e feedbacks de forma profissional e com abertura para crescimento.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Comportamental','COM5','Age com ética e discrição no exercício da função.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Comportamental','COM6','Mantém controle emocional e profissionalismo em situações de alta pressão.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Liderança Situacional','LS1','Participa ativamente do trabalho em equipe, comunicando e recebendo informações de forma clara e organizada.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Liderança Situacional','LS2','Mantém atenção à situação da ocorrência, acompanhando o estado do paciente, os equipamentos e as condições do ambiente.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Liderança Situacional','LS3','Demonstra compromisso com a segurança, utilizando corretamente os EPIs e adotando medidas de proteção para si, para o paciente e para a equipe.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Liderança Situacional','LS4','Mantém foco e equilíbrio emocional em situações de pressão, agindo com profissionalismo e respeito.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Processo e Qualidade','PQ1','Preenche corretamente os registros de atendimento com informações precisas e no tempo adequado.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Técnico de Enfermagem','Processo e Qualidade','PQ2','Executa o transporte seguro de pacientes críticos, sem agravar lesões existentes.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado');
INSERT INTO public.criterios_avaliacao (tipo,categoria,codigo,criterio,indicador,ativo,created_at,peso,avaliacao) VALUES
	 ('Enfermeiro','Técnico / Clínico','ETC1','Realiza avaliação clínica completa (SAMPLA, ABCDE, Glasgow, FAST) e formula diagnósticos de enfermagem precisos.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Enfermeiro','Técnico / Clínico','ETC2','Executa com precisão procedimentos de SAV: acesso venoso difícil, intubação orotraqueal, RCP avançada e desfibrilação.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Enfermeiro','Técnico / Clínico','ETC3','Administra medicamentos de urgência com segurança, verificando prescrição, dose, via e tempo de administração.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Enfermeiro','Técnico / Clínico','ETC4','Toma decisões clínicas rápidas e assertivas em cenários de IAM, AVC, trauma grave, sepse e PCR.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Enfermeiro','Técnico / Clínico','ETC5','Reconhece limitações técnicas e aciona o médico regulador/intervencionista nos momentos adequados.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Enfermeiro','Técnico / Clínico','ETC6','Supervisiona o técnico de enfermagem e o condutor, orientando procedimentos e prevenindo erros.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Enfermeiro','Liderança','ELD1','Exerce liderança na USB/USA: dirige a equipe com clareza, distribui tarefas e coordena o atendimento.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Enfermeiro','Liderança','ELD2','Organiza as tarefas sequencialmente, priorizando intervenções conforme gravidade e tempo-crítico.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Enfermeiro','Liderança','ELD3','Mantém e compartilha a consciência situacional com toda a equipe (briefing e atualização contínua).',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Enfermeiro','Liderança','ELD4','Encontra soluções criativas e adequadas diante de cenários complexos ou com recursos limitados.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado');
INSERT INTO public.criterios_avaliacao (tipo,categoria,codigo,criterio,indicador,ativo,created_at,peso,avaliacao) VALUES
	 ('Enfermeiro','Liderança','ELD5','Lidera pelo exemplo no uso correto de EPIs e na aplicação de precauções de segurança em toda a cena.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Enfermeiro','Comportamental','ECO1','Registra o Processo de Enfermagem de forma completa, legível e juridicamente válida.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Enfermeiro','Comportamental','ECO2','Contribui para as metas operacionais: tempo-resposta ≤ 15min, tempo de cena ≤ 20min e ROSC em PCR.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Enfermeiro','Comportamental','ECO3','Mantém postura ética e discrição absoluta em todas as situações de atendimento.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Enfermeiro','Comportamental','ECO4','Demonstra responsabilidade e comprometimento, sendo referência de conduta para a equipe.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Enfermeiro','Comportamental','ECO5','Mantém comunicação clara, respeitosa e empática com pacientes, familiares e equipe.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('BP-TEAM','Criterio aqui','Codigo','Pergunta aqui','Indicador',false,'2026-06-10 13:35:37.504952',1,'autoavaliacao'),
	 ('Médico','Técnico / Clínico','MTC1','Realiza avaliação clínica completa e rápida, formulando diagnóstico sindromático correto no pré-hospitalar.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Médico','Técnico / Clínico','MTC2','Executa procedimentos de SAV com excelência: IOT difícil, acesso intraósseo, drenagem e cardioversão.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Médico','Técnico / Clínico','MTC3','Aplica o protocolo de IAM (ACLS): ECG, trombolítico, ativação hemodinâmica; cumpre o tempo porta-balão ≤ 90min.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado');
INSERT INTO public.criterios_avaliacao (tipo,categoria,codigo,criterio,indicador,ativo,created_at,peso,avaliacao) VALUES
	 ('Médico','Técnico / Clínico','MTC4','Aplica o protocolo de AVC (FAST/NIHSS) e aciona a linha de cuidado cerebrovascular conforme POP.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Médico','Técnico / Clínico','MTC5','Conduz a PCR conforme ACLS: algoritmo, ritmo, medicação, tempo de RCP e ROSC — com taxa de retorno adequada.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Médico','Técnico / Clínico','MTC6','Comunica-se eficientemente com o médico regulador da CRUR-BF: informações precisas, decisão conjunta e tempo de regulação.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Médico','Técnico / Clínico','MTC7','Prescreve, verifica e supervisiona a administração de medicamentos de urgência com segurança e precisão.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Médico','Liderança','MLD1','Lidera a equipe USA com autoridade, clareza e empatia: define papéis, distribui tarefas e mantém a segurança.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Médico','Liderança','MLD2','Gerencia simultaneamente múltiplas tarefas críticas: paciente, equipe, comunicação com regulação e documentação.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Médico','Liderança','MLD3','Toma decisões rápidas e assertivas sob pressão extrema, com base em evidências e priorização correta.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Médico','Liderança','MLD4','Mantém consciência situacional ampla (cena, paciente, equipe, recursos, tempo) e adapta o plano de cuidado.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Médico','Liderança','MLD5','Utiliza comunicação em loop com a equipe, confirmando ordens e mantendo registro verbal das condutas.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Médico','Comportamental','MCO1','Documenta o atendimento médico de forma completa: hipótese diagnóstica, condutas, medicamentos e encaminhamento.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado');
INSERT INTO public.criterios_avaliacao (tipo,categoria,codigo,criterio,indicador,ativo,created_at,peso,avaliacao) VALUES
	 ('Médico','Comportamental','MCO2','Aborda paciente e família com empatia, respeito, escuta ativa e informação adequada mesmo em cenários críticos.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Médico','Comportamental','MCO3','Mantém postura ética e discrição absoluta em todas as situações de atendimento.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Médico','Comportamental','MCO4','Demonstra responsabilidade e comprometimento, sendo referência de conduta profissional para toda a equipe.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Médico','Comportamental','MCO4','Contribui para o cumprimento dos indicadores de qualidade operacional e clínica.',NULL,false,'2026-06-16 14:33:45.376645',1,'Lider > Liderado'),
	 ('Médico','Trabalho em Equipe','3','Sou receptivo(a) a feedbacks construtivos da equipe após uma ocorrência.','',true,'2026-06-11 17:48:02.009131',1,'autoavaliacao'),
	 ('Enfermeiro','Liderança','EN-L4','Mantém e compartilha a consciência situacional com toda a equipe (briefing / atualização contínua)','Consciência situacional coletiva',false,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Trabalho em Equipe','a4','Sou receptivo(a) a feedbacks construtivos da equipe após uma ocorrência.','',true,'2026-06-11 18:10:30.85717',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','teste','teste','teste','teste',false,'2026-06-16 15:06:24.55669',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','teste','teste','teste','teste',false,'2026-06-16 15:06:24.382685',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','teste','teste','teste','teste',false,'2026-06-16 15:06:21.75744',1,'autoavaliacao');
INSERT INTO public.criterios_avaliacao (tipo,categoria,codigo,criterio,indicador,ativo,created_at,peso,avaliacao) VALUES
	 ('Técnico de Enfermagem','teste','teste','teste','teste',false,'2026-06-16 15:06:24.807627',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','teste','teste','teste','teste',false,'2026-06-16 15:06:18.555715',1,'autoavaliacao'),
	 ('BP-TEAM','Gerenciamento de Tarefas','BT-GT2','As intervenções são priorizadas corretamente conforme critérios de gravidade e tempo-crítico','',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('BP-TEAM','Habilidades Não Técnicas (NTS)','BT-NTS1','A equipe demonstra consciência situacional compartilhada: cena, paciente, recursos, tempo','',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('BP-TEAM','Gerenciamento de Tarefas','BT-GT3','Os procedimentos são executados com técnica correta, sem erros ou omissões significativas','',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('BP-TEAM','Trabalho em Equipe','BT-TT1','A equipe utiliza comunicação em loop fechado (call-out + check-back) de forma consistente','',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('BP-TEAM','Trabalho em Equipe','BT-TT3','Todos os membros compartilham o mesmo modelo mental do quadro clínico e plano de ação','',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Técnico-Clínico','TE-T1','Realiza avaliação primária (ABCDE) de forma rápida, sistemática e correta após chegada na cena','Avaliação primária ABCDE',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Técnico-Clínico','TE-T2','Identifica e comunica sinais de gravidade imediata ao Enfermeiro/médico com precisão e agilidade','Triagem e comunicação',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Técnico-Clínico','TE-T3','Executa corretamente compressões torácicas, ventilação (bolsa-valva-máscara) e desfibrilação com DEA conforme protocolo','RCP e DEA',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao');
INSERT INTO public.criterios_avaliacao (tipo,categoria,codigo,criterio,indicador,ativo,created_at,peso,avaliacao) VALUES
	 ('Técnico de Enfermagem','Técnico-Clínico','TE-T4','Realiza punção venosa periférica, coleta e administra medicamentos conforme prescrição do Enfermeiro/médico','Punção venosa / medicação',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Técnico-Clínico','TE-T5','Manuseia corretamente: oxímetro, monitor cardíaco, respirador, glicosímetro e demais equipamentos da USB/USA','Manuseio de equipamentos',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Técnico-Clínico','TE-T6','Realiza imobilização adequada de vítimas de trauma (colar cervical, prancha, talas) conforme protocolo PHTLS','Imobilização PHTLS',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Técnico-Clínico','TE-T7','Executa técnica correta de movimentação e transporte de pacientes críticos sem agravar lesões','Técnica de transporte',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Técnico-Clínico','TE-T8','Conhece e segue os protocolos clínicos do SAMU-192 (sepse, IAM, AVC, trauma, PCR, intoxicação)','Adesão a protocolos',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Comportamental','TE-B1','Participa ativamente do trabalho em equipe, recebe e transmite informações de forma padronizada (SBAR)','Comunicação SBAR / trabalho em equipe',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Comportamental','TE-B2','Mantém consciência situacional: monitora o estado do paciente, equipamentos e ambiente simultaneamente','Consciência situacional NTS',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Comportamental','TE-B3','Usa corretamente todos os EPIs e adota medidas de segurança para si, paciente e equipe em toda cena','Segurança / EPIs',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Comportamental','TE-B4','Mantém foco e equilíbrio emocional em situações de alta pressão (PCR, múltiplas vítimas, violência)','Controle emocional',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Processo e Qualidade','TE-P1','Preenche corretamente a ficha de atendimento pré-hospitalar com completude, clareza e fidelidade aos achados','Qualidade do prontuário',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao');
INSERT INTO public.criterios_avaliacao (tipo,categoria,codigo,criterio,indicador,ativo,created_at,peso,avaliacao) VALUES
	 ('Condutor','Comportamental','C-B2','Comunica-se de forma clara e objetiva com a equipe e com a Central de Regulação (CRUR-BF) durante o atendimento','Comunicação operacional',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Condutor','Técnico-Operacional','C-T1','Realiza checklist completo da viatura no início do plantão (combustível, pneus, equipamentos, kit de emergência)','Checklist preenchido',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Condutor','Técnico-Operacional','C-T3','Mantém a ambulância limpa, organizada e em condições sanitárias adequadas após cada atendimento','Higienização ambulância',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Condutor','Técnico-Operacional','C-T5','Conhece e utiliza corretamente rotas de acesso, vias alternativas e GPS para otimização do tempo-resposta','Geolocalização / rotas',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','teste','teste','teste','teste',false,'2026-06-16 15:06:20.360317',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','teste','teste','teste','teste',false,'2026-06-16 15:06:21.094899',1,'autoavaliacao'),
	 ('Condutor','Técnico-Operacional','C-T6','Auxilia a equipe nos procedimentos de Suporte Básico de Vida (SBV): RCP, imobilização, oxigenoterapia básica','Competência SBV',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Condutor','Técnico-Operacional','C-T4','Pratica direção defensiva com habilidade, respeitando sinalização e segurança da equipe e paciente no deslocamento de emergência','Direção defensiva',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Condutor','Técnico-Operacional','C-T7','Manuseia corretamente a maca, cadeira de rodas, prancha longa e colar cervical','Manuseio de equipamentos',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Condutor','Comportamental','C-B6','Trata pacientes, familiares e equipe com respeito, sigilo e ética, respeitando a dignidade humana','Ética e humanização',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao');
INSERT INTO public.criterios_avaliacao (tipo,categoria,codigo,criterio,indicador,ativo,created_at,peso,avaliacao) VALUES
	 ('Condutor','Comportamental','C-B4','Avalia a segurança da cena antes de aproximação e comunica riscos à equipe (tráfego, violência, substâncias)','Segurança da cena',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Condutor','Comportamental','C-B5','Mantém controle emocional em cenários de alta tensão, múltiplas vítimas, violência ou óbito','Controle emocional',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Condutor','Processo e Qualidade','C-P2','Contribui para o cumprimento do tempo-resposta ≤15 minutos da central ao local (Portaria MS 2.048/2002)','Tempo-resposta ≤15min',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Condutor','Processo e Qualidade','C-P1','Preenche corretamente o registro de saída e chegada da viatura, tempo de deslocamento e ocorrências relevantes','Completude dos registros',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Condutor','Comportamental','C-B3','Utiliza corretamente todos os EPIs obrigatórios (luvas, máscara, avental) em todos os atendimentos','Uso de EPIs',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('BP-TEAM','Liderança','BT-L1','O líder dirige a equipe com clareza, define papéis e responsabilidades desde o início do atendimento','',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('BP-TEAM','Liderança','BT-L3','O líder adapta o plano de cuidado conforme evolução clínica do paciente e novos achados da cena','',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('BP-TEAM','Trabalho em Equipe','BT-TT2','Os membros monitoram e apoiam uns aos outros, antecipando necessidades sem solicitação','',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('BP-TEAM','Gerenciamento de Tarefas','BT-GT1','A avaliação do paciente é sistemática (ABCDE), rápida e sem etapas omitidas','',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Condutor','Técnico-Operacional','C-T2','Verifica e registra o estado dos equipamentos médicos (DEA, oxímetro, monitor cardíaco, maca)','Conformidade equipamentos',false,'2026-06-10 10:02:38.389329',1,'autoavaliacao');
INSERT INTO public.criterios_avaliacao (tipo,categoria,codigo,criterio,indicador,ativo,created_at,peso,avaliacao) VALUES
	 ('Condutor','teste','C-B1','Comunica-se com a equipe, antecipando necessidades, cooperando na cena e comunicando informações relevantes','Trabalho em equipe',false,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Técnico-Clínico','EN-T1','Realiza avaliação clínica completa (SAMPLA, ABCDE, Glasgow, FAST) e formula diagnósticos de enfermagem precisos','Avaliação SAMPLA/ABCDE',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Técnico-Clínico','EN-T5','Toma decisões clínicas rápidas e assertivas em cenários de IAM, AVC, trauma grave, sepse e PCR','Decisão clínica em urgências',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Técnico-Clínico','EN-T6','Reconhece limitações e aciona o médico regulador/intervencionista nos momentos adequados','Escalada de cuidados',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Liderança','EN-L2','Usa comunicação em loop fechado (call-out, check-back) para garantir compreensão das ordens na cena','Comunicação em loop (NTS)',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Liderança','EN-L3','Organiza as tarefas sequencialmente, priorizando intervenções conforme gravidade e tempo-crítico','Gerenciamento de tarefas (bp-TEAM)',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Comportamental','EN-B1','Lidera pelo exemplo no uso de EPIs e na aplicação de precauções de segurança em toda a cena','Segurança do paciente e equipe',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Processo e Qualidade','EN-P1','Registra o Processo de Enfermagem no SAMU de forma completa, legível e juridicamente válida','Completude do Registro PE/SAMU (IVC ≥0,80)',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Processo e Qualidade','EN-P2','Contribui para metas operacionais: tempo-resposta ≤15min, tempo de cena ≤20min, ROSC em PCR','KPIs operacionais',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Médico','Técnico-Clínico','MD-T1','Realiza avaliação clínica completa e rápida, formulando diagnóstico sindromático correto no pré-hospitalar','Diagnóstico pré-hospitalar',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao');
INSERT INTO public.criterios_avaliacao (tipo,categoria,codigo,criterio,indicador,ativo,created_at,peso,avaliacao) VALUES
	 ('Médico','Técnico-Clínico','MD-T2','Executa procedimentos de SAV com excelência: IOT difícil, acesso intraósseo, drenagem, cardioversão','Procedimentos SAV avançados',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Médico','Técnico-Clínico','MD-T5','Conduz a PCR conforme ACLS: algoritmo, ritmo, medicação, tempo de RCP, ROSC — taxa de retorno adequada','PCR / ROSC (taxa retorno circulação)',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Médico','Técnico-Clínico','MD-T6','Comunica-se eficientemente com o médico regulador da CRUR-BF: informações precisas, decisão conjunta, tempo de regulação','Qualidade da telemedicina / regulação',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Médico','Liderança','MD-L1','Lidera a equipe USA com autoridade, clareza e empatia: define papéis, distribui tarefas, mantém hierarquia e segurança','Liderança bp-TEAM (domínio: Liderança)',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Médico','Liderança','MD-L4','Mantém consciência situacional ampla (cena, paciente, equipe, recursos, tempo) e adapta o plano de cuidado','Consciência situacional NTS',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Médico','Liderança','MD-L3','Toma decisões rápidas e assertivas sob pressão extrema, com base em evidências e priorização correta','Tomada de decisão NTS',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Médico','Comportamental','MD-B1','Comunica decisões de forma clara, utiliza comunicação em loop com a equipe e mantém registro verbal de ordens','Comunicação efetiva em loop',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Médico','Comportamental','MD-B2','Aborda paciente e família com empatia, respeito, escuta ativa e informação adequada mesmo em cenários críticos','Humanização do cuidado',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Médico','Liderança','MD-L2','Gerencia simultaneamente múltiplas tarefas críticas: paciente, equipe, comunicação com regulação e documentação','Gerenciamento de tarefas bp-TEAM',false,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Médico','Liderança','MD-L3','Toma decisões rápidas e assertivas sob pressão extrema, com base em evidências e priorização correta','Tomada de decisão NTS',false,'2026-06-10 10:02:38.389329',1,'autoavaliacao');
INSERT INTO public.criterios_avaliacao (tipo,categoria,codigo,criterio,indicador,ativo,created_at,peso,avaliacao) VALUES
	 ('Médico','Processo e Qualidade','MD-P1','Documenta o atendimento médico de forma completa, com hipótese diagnóstica, condutas, medicamentos e encaminhamento','Completude do prontuário médico',false,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Médico','Liderança','MD-L4','Mantém consciência situacional ampla (cena, paciente, equipe, recursos, tempo) e adapta o plano de cuidado','Consciência situacional NTS',false,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Médico','Liderança','MD-L5','Promove o trabalho em equipe, a comunicação efetiva e o ambiente de segurança psicológica para toda a equipe','Clima de equipe / segurança psicológica',false,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Liderança','EN-L1','Exerce liderança na USB/USA: dirige a equipe com clareza, distribui tarefas e coordena o atendimento','Liderança (bp-TEAM: domínio Liderança)',false,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Processo e Qualidade','TE-P2','Repõe materiais e medicamentos utilizados após cada atendimento, mantendo o estoque da viatura padronizado','Reposição de materiais',false,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Técnico-Clínico','EN-T2','Desenvolve e registra o Processo de Enfermagem (PE) conforme CIPE® e protocolos internacionais (PHTLS/ACLS)','Processo de Enfermagem / CIPE®',false,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Liderança','EN-L4','Mantém e compartilha a consciência situacional com toda a equipe (briefing / atualização contínua)','Consciência situacional coletiva',false,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Técnico-Clínico','EN-T7','Supervisiona o técnico de enfermagem e o condutor, orientando procedimentos e prevenindo erros','Supervisão técnica da equipe',false,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Técnico-Clínico','EN-T4','Administra medicamentos de urgência com segurança, verificando via, dose, concentração e registro','Administração de medicamentos',false,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Técnico-Clínico','EN-T3','Executa com precisão procedimentos de SAV: acesso venoso difícil, intubação orotraqueal, RCP avançada, desfibrilação','Procedimentos SAV',false,'2026-06-10 10:02:38.389329',1,'autoavaliacao');
INSERT INTO public.criterios_avaliacao (tipo,categoria,codigo,criterio,indicador,ativo,created_at,peso,avaliacao) VALUES
	 ('Técnico de Enfermagem','Gestão e Liderança','01','Comunica orientações, mudanças de protocolo e feedbacks de forma clara, direta e respeitosa.

','',true,'2026-06-11 17:42:26.875394',1,'autoavaliacao'),
	 ('Médico','Técnico-Clínico','MD-T7','Prescreve, verifica e supervisa a administração de medicamentos de urgência com segurança e precisão','Farmacologia de urgência',false,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('BP-TEAM','Habilidades Não Técnicas (NTS)','BT-NTS2','A equipe mantém desempenho técnico adequado mesmo em cenários de alta carga emocional','',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('BP-TEAM','Liderança','BT-L2','O líder toma decisões de forma assertiva, sem hesitação excessiva, mesmo sob pressão extrema','',true,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Médico','Técnico-Clínico','MD-T4','Aplica protocolo de AVC (FAST/NIHSS), ativação da linha de cuidado cerebrovascular conforme POP','AVC / Protocolo cerebrovascular',false,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Médico','Técnico-Clínico','MD-T3','Aplica protocolo de IAM (ACLS): ECG, trombolítico, ativação hemodinâmica. Tempo porta-balão: cumpre ≤90min','IAM / Tempo porta-balão ≤90min',false,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Médico','Trabalho em Equipe','2','Utilizo comunicação em loop fechado (call-out e check-back) de forma consistente nos atendimentos.','',true,'2026-06-11 17:47:31.017876',1,'autoavaliacao'),
	 ('Médico','Liderança','MD-L2','Gerencia simultaneamente múltiplas tarefas críticas: paciente, equipe, comunicação com regulação e documentação','Gerenciamento de tarefas bp-TEAM',false,'2026-06-10 10:02:38.389329',1,'autoavaliacao'),
	 ('Médico','Habilidades Não Técnicas','4','
Mantenho a calma e o tom de voz firme para estabilizar a equipe, o paciente e os familiares em momentos de desespero ou conflito.','',true,'2026-06-11 17:49:41.318069',1,'autoavaliacao'),
	 ('Condutor','Trabalho em Equipe','a1','Sou receptivo(a) a feedbacks construtivos da equipe após uma ocorrência.','',true,'2026-06-11 17:55:34.775804',1,'autoavaliacao');
INSERT INTO public.criterios_avaliacao (tipo,categoria,codigo,criterio,indicador,ativo,created_at,peso,avaliacao) VALUES
	 ('Condutor','Habilidades Não Técnicas','a2','Realizo a conferência rigorosa da viatura (checklist) no início de cada plantão.','',true,'2026-06-11 17:56:13.906028',1,'autoavaliacao'),
	 ('Técnico de Enfermagem','Trabalho em Equipe','a3','Sou receptivo(a) a feedbacks construtivos da equipe após uma ocorrência.','',true,'2026-06-11 17:58:51.235499',1,'autoavaliacao'),
	 ('Enfermeiro','Técnico-Clínico','TE-T1','Realiza avaliação primária (ABCDE) de forma rápida, sistemática e correta após chegada na cena','Avaliação primária ABCDE',true,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Técnico-Clínico','TE-T3','Executa corretamente compressões torácicas, ventilação (bolsa-valva-máscara) e desfibrilação com DEA conforme protocolo','RCP e DEA',true,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Técnico-Clínico','TE-T6','Realiza imobilização adequada de vítimas de trauma (colar cervical, prancha, talas) conforme protocolo PHTLS','Imobilização PHTLS',true,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Técnico-Clínico','TE-T7','Executa técnica correta de movimentação e transporte de pacientes críticos sem agravar lesões','Técnica de transporte',true,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Comportamental','TE-B1','Participa ativamente do trabalho em equipe, recebe e transmite informações de forma padronizada (SBAR)','Comunicação SBAR / trabalho em equipe',true,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Comportamental','TE-B2','Mantém consciência situacional: monitora o estado do paciente, equipamentos e ambiente simultaneamente','Consciência situacional NTS',true,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Comportamental','TE-B3','Usa corretamente todos os EPIs e adota medidas de segurança para si, paciente e equipe em toda cena','Segurança / EPIs',true,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Comportamental','TE-B4','Mantém foco e equilíbrio emocional em situações de alta pressão (PCR, múltiplas vítimas, violência)','Controle emocional',true,'2026-06-11 15:06:08.472675',1,'autoavaliacao');
INSERT INTO public.criterios_avaliacao (tipo,categoria,codigo,criterio,indicador,ativo,created_at,peso,avaliacao) VALUES
	 ('Enfermeiro','Processo e Qualidade','TE-P1','Preenche corretamente a ficha de atendimento pré-hospitalar com completude, clareza e fidelidade aos achados','Qualidade do prontuário',true,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Processo e Qualidade','TE-P2','Repõe materiais e medicamentos utilizados após cada atendimento, mantendo o estoque da viatura padronizado','Reposição de materiais',true,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Técnico-Clínico','EN-T4','Administra medicamentos de urgência com segurança, verificando via, dose, concentração e registro','Administração de medicamentos',true,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Liderança','EN-L1','Exerce liderança na USB/USA: dirige a equipe com clareza, distribui tarefas e coordena o atendimento','Liderança (bp-TEAM: domínio Liderança)',true,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Liderança','EN-L2','Usa comunicação em loop fechado (call-out, check-back) para garantir compreensão das ordens na cena','Comunicação em loop (NTS)',true,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Liderança','EN-L3','Organiza as tarefas sequencialmente, priorizando intervenções conforme gravidade e tempo-crítico','Gerenciamento de tarefas (bp-TEAM)',true,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Técnico-Clínico','EN-T1','Realiza avaliação clínica completa (SAMPLA, ABCDE, Glasgow, FAST) e formula diagnósticos de enfermagem precisos','Avaliação SAMPLA/ABCDE',false,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Técnico-Clínico','TE-T2','Identifica e comunica sinais de gravidade imediata ao Enfermeiro/médico com precisão e agilidade','Triagem e comunicação',false,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Técnico-Clínico','TE-T4','Realiza punção venosa periférica, coleta e administra medicamentos conforme prescrição do Enfermeiro/médico','Punção venosa / medicação',false,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Técnico-Clínico','TE-T8','Conhece e segue os protocolos clínicos do SAMU-192 (sepse, IAM, AVC, trauma, PCR, intoxicação)','Adesão a protocolos',false,'2026-06-11 15:06:08.472675',1,'autoavaliacao');
INSERT INTO public.criterios_avaliacao (tipo,categoria,codigo,criterio,indicador,ativo,created_at,peso,avaliacao) VALUES
	 ('Enfermeiro','Técnico-Clínico','EN-T7','Supervisiona o Enfermeiro e o condutor, orientando procedimentos e prevenindo erros','Supervisão técnica da equipe',false,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Técnico-Clínico','EN-T2','Desenvolve e registra o Processo de Enfermagem (PE) conforme CIPE® e protocolos internacionais (PHTLS/ACLS)','Processo de Enfermagem / CIPE®',false,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Técnico-Clínico','EN-T6','Reconhece limitações e aciona o médico regulador/intervencionista nos momentos adequados','Escalada de cuidados',false,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Técnico-Clínico','TE-T5','Manuseia corretamente: oxímetro, monitor cardíaco, respirador, glicosímetro e demais equipamentos da USB/USA','Manuseio de equipamentos',false,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Técnico-Clínico','EN-T5','Toma decisões clínicas rápidas e assertivas em cenários de IAM, AVC, trauma grave, sepse e PCR','Decisão clínica em urgências',false,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Processo e Qualidade','EN-P1','Registra o Processo de Enfermagem no SAMU de forma completa, legível e juridicamente válida','Completude do Registro PE/SAMU (IVC ≥0,80)',true,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Processo e Qualidade','EN-P2','Contribui para metas operacionais: tempo-resposta ≤15min, tempo de cena ≤20min, ROSC em PCR','KPIs operacionais',true,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Técnico-Clínico','EN-T3','Executa com precisão procedimentos de SAV: acesso venoso difícil, intubação orotraqueal, RCP avançada, desfibrilação','Procedimentos SAV',false,'2026-06-11 15:06:08.472675',1,'autoavaliacao'),
	 ('Enfermeiro','Processo e Qualidade','MD-P1','Documenta o atendimento médico de forma completa, com hipótese diagnóstica, condutas, medicamentos e encaminhamento','Completude do prontuário médico',false,'2026-06-11 15:04:42.69826',1,'autoavaliacao'),
	 ('Enfermeiro','Comportamental','EN-B1','Lidera pelo exemplo no uso de EPIs e na aplicação de precauções de segurança em toda a cena','Segurança do paciente e equipe',false,'2026-06-11 15:06:08.472675',1,'autoavaliacao');
